# This is a basic workflow to help you get started with Actions

name: Build release image

# Controls when the workflow will run
on:
  push:
    branches:
      - releases/v*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: f12/${{ github.event.repository.name }}
          flavor: |
            latest=false
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::${GITHUB_SHA::7}"

      - name: echo meta
        run: echo "Tags = ${{ join(fromJSON(steps.meta.outputs.json).tags) }}, f12/${{ github.event.repository.name }}:${{ steps.vars.outputs.sha_short }}, f12/${{ github.event.repository.name }}:staging"

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Build the image
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag f12/${{ github.event.repository.name }}:${{ steps.vars.outputs.sha_short }}

      # Push to ECR
      - name: Push release to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: eu-west-1
          local-image: f12/${{ github.event.repository.name }}:${{ steps.vars.outputs.sha_short }}
          image: ${{ join(fromJSON(steps.meta.outputs.json).tags) }}, f12/${{ github.event.repository.name }}:${{ steps.vars.outputs.sha_short }}, f12/${{ github.event.repository.name }}:staging
